### PR TITLE
chore(bower): add .bower.json (already registred)

### PR DESCRIPTION
**Pull request by edouard-lopez**
I created a .bower.json and registred it using

```
bower register webL10n git@github.com:edouard-lopez/webL10n.git
```

So now you can simply install it using:

```
bower install webL10n
```

More info on registering package at https://github.com/bower/bower#registering-packages

**N.B.:** I will update the endpoint to your repo when the request is merge into your repo.

### CODE REVIEW

**Comment by askmatey** [comment]
:+1:

**Comment by Rob--W** [comment]
Could you transfer the ownership of the bower package to a webL10n maintainer? That's either Fabien or me.

**Comment by gazal-k** [comment]
@edouard-lopez a few thoughts on this:

 - it might get to tricky it the version numbers for the npm and bower packages don't match.
 - the maintainers will have to create proper semver tags for this to work correctly, right?

**Comment by gazal-k** [comment]
Just noticed how old this PR is. Missing quite a lot of new changes: https://github.com/edouard-lopez/webL10n/compare/master...fabi1cazenave:master

Guys, please sort this out so that we can have an updated bower package.

In the meantime I've created my own fork and added a bower.json, https://github.com/gazal-k/webL10n.
So if anyone wants to get the updated bower package:
```js
"webL10n": "gazal-k/webL10n#*"
```

**Comment by edouard-lopez** [comment]
@Rob--W any idea how to transfer ownership ?

**Comment by edouard-lopez** [comment]
@gazal-k the PR just add a `bower.json` file and as you can see at the bottom of this thread, it's still up-to-date with the base branch. I just need to be merged.

**Comment by gazal-k** [comment]
@edouard-lopez that's right. But I was only saying that the bower dependency is not up to date.

**Comment by Rob--W** [comment]
@edouard-lopez To transfer the ownership of the package, you have to unregister it so that I can register it. We have to schedule a convenient time so that the bower registration is not stolen by someone else (please follow up by mail to avoid targeted attacks).

**Comment by askmatey** [comment]
@fat and @maccman

**Comment by askmatey** [comment]
https://github.com/orgs/bower/people or opensource@twitter.com

**Comment by askmatey** [comment]
@Rob--W I smell a high level of dangerosity

**Pull request closed without merging**
